# Generated by Django 2.1.2 on 2018-10-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('status', models.IntegerField()),
                ('currentLatitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('currentLongitude', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('ccName', models.CharField(max_length=200)),
                ('ccType', models.CharField(max_length=200)),
                ('ccNumber', models.CharField(max_length=200)),
                ('ccExpirationDate', models.CharField(max_length=200)),
                ('ccIsDefault', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='allowDetour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
