# Generated by Django 2.1.2 on 2018-10-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20181004_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.IntegerField(default=-1),
        ),
    ]
