# Generated by Django 2.1.2 on 2018-10-05 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20181004_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='currentLatitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='driver',
            name='currentLongitude',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ccIsDefault',
            field=models.BooleanField(null=True),
        ),
    ]
