# Generated by Django 2.1.2 on 2018-10-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20181005_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='ccExpirationDate',
        ),
        migrations.AddField(
            model_name='payment',
            name='ccCVV',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='ccExpirationMonth',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='ccExpirationYear',
            field=models.IntegerField(default=0),
        ),
    ]
