# Generated by Django 2.1.2 on 2018-10-13 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20181005_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='userId',
            field=models.IntegerField(unique=True),
        ),
    ]
