# Generated by Django 2.1.2 on 2018-10-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20181012_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='currentLatitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='currentLongitude',
            field=models.FloatField(default=0),
        ),
    ]
