# Generated by Django 2.1.2 on 2018-10-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20181013_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
