# Generated by Django 2.1.2 on 2018-10-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20181019_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='userId',
            field=models.IntegerField(default=None),
        ),
    ]
