# Generated by Django 2.1.2 on 2018-10-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20181019_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='userId',
            field=models.IntegerField(null=True),
        ),
    ]
