# Generated by Django 2.1.2 on 2018-10-21 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20181019_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='fixedDriverId',
            field=models.IntegerField(null=True),
        ),
    ]
