# Generated by Django 2.1.2 on 2018-11-03 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_driver_fixeddriverid'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverId', models.IntegerField()),
                ('userId', models.IntegerField(null=True)),
                ('customerLatitude', models.FloatField(default=0)),
                ('customerLongitude', models.FloatField(default=0)),
                ('destinationLatitude', models.FloatField(default=0)),
                ('destinationLongitude', models.FloatField(default=0)),
                ('driverLatitude', models.FloatField(default=0)),
                ('driverLongitude', models.FloatField(default=0)),
            ],
        ),
    ]
