# Generated by Django 2.1.2 on 2018-11-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_riderequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequests',
            name='isAccepted',
            field=models.IntegerField(null=True),
        ),
    ]
