# Generated by Django 2.1.2 on 2018-11-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20181105_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequests',
            name='isAccepted',
            field=models.IntegerField(default=0),
        ),
    ]
