# Generated by Django 2.1.2 on 2018-11-06 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_auto_20181105_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderequests',
            old_name='isAccepted',
            new_name='accepted',
        ),
    ]
