# Generated by Django 2.1.3 on 2018-11-18 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20181105_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='allowDetour',
        ),
    ]
