# Generated by Django 2.1.2 on 2018-11-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='userId',
            field=models.IntegerField(null=True),
        ),
    ]
