# Generated by Django 2.1.2 on 2018-11-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_address_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='zip',
        ),
        migrations.AddField(
            model_name='address',
            name='zipCode',
            field=models.IntegerField(default=94544),
        ),
        migrations.AlterField(
            model_name='address',
            name='userId',
            field=models.IntegerField(),
        ),
    ]
